
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <!-- specify the main method entry point -->
      <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  <!-- Enable OpenXR scaffold code and start OpenGL session scaffolding -->
  <DefineConstants>$(DefineConstants);USE_OPENXR;OPENXR_GL_IMPLEMENTED</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="AstroTestGame\**" />
    <EmbeddedResource Remove="AstroTestGame\**" />
    <None Remove="AstroTestGame\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CSCore" Version="1.2.1.2" />
    <PackageReference Include="Evergine.Bindings.OpenXR" Version="2025.9.1.27" />
    <PackageReference Include="FNA.NET" Version="2.1.2.2506" />
    <PackageReference Include="OpenTK" Version="4.9.4" />
    <PackageReference Include="SixLabors.Fonts" Version="2.1.3" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.11" />
    <PackageReference Include="SixLabors.ImageSharp.Drawing" Version="2.1.7" />
    <ProjectReference Include="..\SharpMASM\SharpMASM.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets/UIFont.ttf" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Window\Keyboard\" />
  </ItemGroup>

</Project>
